services:
    _defaults:
        autowire: true
        autoconfigure: true
        
    Vankosoft\CatalogBundle\Controller\ProductController:
        autowire: false
        public: true
        
    App\Controller\AdminPanel\BooksController:
        autowire: false
        public: true
    
    App\Controller\AdminPanel\DefaultController:
        tags: ['controller.service_arguments']

    App\Controller\Application\DebugController:
        tags: ['controller.service_arguments']
        
    App\Controller\AdminPanel\AuthorExtController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vs_reading_room.repository.book_author'
    
    App\Controller\AdminPanel\ProductExtController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vs_catalog.repository.product'
            - '@vs_catalog.repository.product_category'
            - '@vs_application.repository.taxonomy'
            - '@vs_application.repository.tags_whitelist_context'
            #- '@vs_catalog.resources.product.form'
