parameters:
    # If you have different path for menu configuration set it here
    #vs_application.menu.config_file: "%kernel.project_dir%/config/admin-panel/packages/vs_application.yaml"
    
    # If You create Any Custom Menue, add it to menus array to can use for breadcrumbs
    vs_application.main_menus:
        - 'profileMenu'
        - 'mainSystemMenu'
        - 'mainCmsMenu'
        - 'mainUsersSubscriptionsMenu'
        - 'mainPaymentMenu'
        - 'mainCatalogMenu'
        - 'mainReadingRoomMenu'

services:
    # Custom Menus
    ######################################################
    vs_reading_room.main_menu_reading_room:
        autowire: false
        class: Knp\Menu\MenuItem
        factory: ["@vs_app.menu_builder", mainMenu]
        arguments: ["@knp_menu.factory", 'mainReadingRoomMenu']
        tags:
            - { name: knp_menu.menu, alias: mainReadingRoom }
