parameters:
    # Gaufrette File Systems
    vs_cms.gaufrette.app_pictures.filesystem: vs_application_app_pictures
    vs_cms.gaufrette.profile.filesystem: vs_application_profile
    vs_cms.gaufrette.filemanager.filesystem: vs_application_filemanager
    vs_cms.gaufrette.slider.filesystem: vs_application_slider
    
    # Gaufrette Shared Media Directories
    vs_cms.filemanager_shared_media_gaufrette.app_pictures: "%kernel.project_dir%/public/shared_media/gaufrette/app_pictures"
    vs_cms.filemanager_shared_media_gaufrette.profile: "%kernel.project_dir%/public/shared_media/gaufrette/profile"
    vs_cms.filemanager_shared_media_gaufrette.filemanager: "%kernel.project_dir%/public/shared_media/gaufrette/filemanager"
    vs_cms.filemanager_shared_media_gaufrette.slider: "%kernel.project_dir%/public/shared_media/gaufrette/slider"
    
    # Artgris Shared Media Directories
    vs_cms.filemanager_shared_media_artgris: '%kernel.project_dir%/public/shared_media/artgris'
    
    # ReadingRoom Shared Media Directories
    vs_reading_room.filemanager_shared_media_gaufrette.books: "%kernel.project_dir%/public/shared_media/gaufrette/books"
    vs_reading_room.gaufrette.books.filesystem: vs_reading_room_books

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    
    # Create a Custom Uploader extending Vankosoft\CmsBundle\Component\Uploader\FilemanagerUploader
    # Add Needed Configurations in packages/knp_gaufrette.yaml
    ##################################################################################################
#    vs_application.custom_uploader:
#        class: App\Component\Uploader\GamePictureUploader
#        arguments:
#            - '@vs_application.app_pictures_uploader.filesystem'
#            - '@vs_cms.file_path_generator'
        
    vs_reading_room.book_uploader:
        class: App\Component\Uploader\BookUploader
        arguments:
            - '@oneup_flysystem.vs_reading_room_books_filesystem'
            - '@vs_cms.file_path_generator'
