#app_vs_catalog_products:
#    resource: "@VSCatalogBundle/Resources/config/routing/products.yaml"
#    prefix: /




# app_vs_catalog_catalog:
#     resource: "@VSCatalogBundle/Resources/config/routing/catalog.yaml"
#     prefix: /

vs_catalog_catalog_latest_products:
    path: /catalog/books
    controller: App\Controller\ReadingRoom\CatalogController::latestProductsAction
    
vs_catalog_catalog_category_products:
    path: /catalog/books/{categorySlug}
    controller: App\Controller\ReadingRoom\CatalogController::categoryProductsAction
    defaults:
        categorySlug: ''
    
vs_catalog_catalog_product_show:
    path: /catalog/books/{categorySlug}/{productSlug}
    controller: App\Controller\ReadingRoom\CatalogController::showProductAction
    defaults:
        categorySlug: ''
        productSlug: ''





app_vs_catalog_pricing_plans:
    resource: "@VSCatalogBundle/Resources/config/routing/pricing_plans.yaml"
    prefix: /
    
app_vs_catalog_payment:
    resource: "@VSCatalogBundle/Resources/config/routing/payment.yaml"
    prefix: /
    
vs_payment_show_payment_methods_form:
    path: /payment-methods
    controller: App\Controller\ReadingRoom\ShoppingCartCheckoutController::showPaymentMethodsFormAction
    options:
        expose: true
        
vs_payment_pricing_plans:
    path: /pricing-plans-checkout
    controller: App\Controller\ReadingRoom\PricingPlanCheckoutController::showPricingPlans
    options:
        expose: true


