app_vs_catalog_pricing_plans:
    resource: "@VSCatalogBundle/Resources/config/routing/pricing_plans.yaml"
    prefix: /
    
app_vs_catalog_payment:
    resource: "@VSCatalogBundle/Resources/config/routing/payment.yaml"
    prefix: /
    
app_vs_catalog_products:
    resource: "@VSCatalogBundle/Resources/config/routing/products.yaml"
    prefix: /
    
app_vs_catalog_catalog:
    resource: "@VSCatalogBundle/Resources/config/routing/catalog.yaml"
    prefix: /

#########################################################################
# Overide Some Routes
#########################################################################
vs_catalog_catalog_latest_products:
    path: /catalog/products/latest
    controller: App\Controller\ReadingRoom\CatalogController::latestProductsAction
    
vs_catalog_catalog_category_products:
    path: /catalog/products/{categorySlug}
    controller: App\Controller\ReadingRoom\CatalogController::categoryProductsAction
    defaults:
        categorySlug: ''
